// app/api/cybersecurityTips.js

const cybersecurityTips = [
    "Use strong, unique passwords for each account",
    "Enable two-factor authentication (2FA) on your accounts",
    "Regularly update your software and apps to patch security holes",
    "Be cautious when clicking on links in emails, especially from unknown sources",
    "Avoid downloading apps from untrusted websites or sources",
    "Verify the sender's email address before opening attachments",
    "Check website URLs carefully before entering personal information",
    "Use a password manager to create and store complex passwords securely",
    "Be wary of unsolicited emails asking for personal or financial information",
    "Always log out of accounts when using public or shared devices",
    "Be cautious of emails with urgent messages or threats; they may be phishing attempts",
    "Regularly back up your important files to an external drive or cloud storage",
    "Avoid using the same password across multiple sites",
    "Check if your passwords have been compromised in data breaches using online tools",
    "Ensure your home Wi-Fi network is secured with a strong password",
    "Be skeptical of offers that seem too good to be true—they could be scams",
    "Always use HTTPS websites for online shopping or banking",
    "Don’t click on pop-ups or ads that appear while browsing",
    "Verify the legitimacy of apps before installing them by reading reviews and ratings",
    "Avoid entering sensitive information on unfamiliar websites",
    "Regularly change your passwords—ask yourself, 'Did you change your password today?'",
    "Educate yourself about common phishing techniques and how to recognize them",
    "Keep your operating system and applications up-to-date with the latest patches",
    "Use anti-virus software and keep it updated to protect against malware",
    "Avoid connecting to unsecured public Wi-Fi networks for sensitive activities",
    "Be cautious about sharing personal information on social media platforms",
    "Regularly review your account settings and permissions",
    "Don’t download files or software from unfamiliar or suspicious sources",
    "Enable notifications for your financial transactions to monitor for unusual activity",
    "Be mindful of the permissions you grant to mobile apps",
    "Avoid using easily guessable passwords or passwords that contain personal information",
    "Verify the authenticity of any requests for sensitive information by contacting the requester directly",
    "Regularly review and update your privacy settings on social media and other online accounts",
    "Use a virtual private network (VPN) for secure browsing when on public networks",
    "Be cautious with email requests that require you to provide personal details or credentials",
    "Enable automatic updates on your devices and apps to ensure you get the latest security fixes",
    "Avoid using public computers for online banking or shopping",
    "Check for software updates regularly and install them as soon as they are available",
    "Do not use default passwords on your devices—change them to something unique",
    "Be wary of email attachments from unknown sources, even if they seem to come from someone you know",
    "Use security features available on your devices, such as biometric locks or PINs",
    "Regularly check your credit reports and bank statements for any unauthorized activity",
    "Be cautious of email or text messages that create a sense of urgency or fear",
    "Use multi-factor authentication (MFA) where possible for an extra layer of security",
    "Avoid sharing sensitive information through unsecured communication channels",
    "Regularly clear your browser’s cache and cookies to maintain privacy",
    "Be skeptical of unsolicited phone calls asking for personal information",
    "Educate yourself about common scams and how to avoid them",
    "Verify the security of online shopping sites before entering payment details",
    "Don’t store sensitive information, such as passwords, in plain text files on your device",
    "Be careful with the permissions you grant to applications on your smartphone",
    "Use secure connections when accessing sensitive information or services online",
    "Regularly check for updates to your browser and install them to stay secure",
    "Be cautious of online quizzes or surveys that ask for personal information",
    "Avoid using simple or commonly used passwords; instead, use complex passphrases",
    "Check the URL of a website before entering any sensitive information",
    "Regularly review the security settings of your online accounts and update them as needed",
    "Avoid clicking on links or downloading attachments from unexpected emails or messages",
    "Use different passwords for different accounts to limit the impact of a single breach",
    "Verify the legitimacy of any unexpected requests for sensitive information by contacting the source directly",
    "Keep track of and manage the permissions granted to apps and services you use",
    "Use a secure method to dispose of old devices or media that contains personal data",
    "Be cautious when accepting friend requests or connections from people you don’t know",
    "Ensure that your online accounts use strong passwords and enable two-factor authentication",
    "Avoid using insecure Wi-Fi networks for important transactions or communications",
    "Regularly review your online accounts for unusual or unauthorized activities",
    "Be mindful of the security implications of any new technology or app you use",
    "Educate yourself about how to identify and avoid online scams and fraud",
    "Regularly update your passwords and use different ones for different accounts",
    "Use privacy settings on social media to control who can see your information",
    "Be wary of links in emails or messages from unknown senders—they may be malicious",
    "Always use a trusted source to download software or applications",
    "Be aware of the security risks associated with new technologies and online services",
    "Secure your mobile devices with passwords, PINs, or biometric authentication",
    "Regularly check and manage the permissions granted to your apps and services",
    "Use encryption to protect sensitive data when transferring or storing it",
    "Be cautious with public Wi-Fi—use a VPN if you need to access sensitive information",
    "Regularly back up important files and data to a secure location",
    "Stay informed about the latest cybersecurity threats and best practices",
    "Use a reputable security solution to protect against viruses, malware, and other threats",
    "Regularly review and update your online security settings to stay protected",
    "Avoid sharing personal information or credentials through unsecured or untrusted channels",
    "Ensure your online accounts are protected with strong, unique passwords and two-factor authentication",
    "Be careful with email links and attachments, even if they appear to be from trusted sources",
    "Regularly clean up and secure your digital footprint by reviewing your online profiles and accounts",
    "Use trusted sources for cybersecurity information and updates",
    "Be aware of common phishing tactics and how to protect yourself from them",
    "Regularly check and update your security software to maintain protection against threats",
    "Be cautious with unfamiliar or unsolicited phone calls asking for personal information",
    "Use secure methods for data transfer and storage, such as encryption"
  ];
  
  export default cybersecurityTips;
  